services:
  accounts:
    image: "mahidhar/accounts:1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mahidhar
  loans:
    image: "mahidhar/loans:1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mahidhar
  cards:
    image: "mahidhar/cards:1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - mahidhar
networks:
  mahidhar:
    driver: "bridge"