build:
  version: "3.0"


accounts:
  message: "Welcome to OneBank accounts related local APIs "
  contactDetails:
    name: "John Diesel - Developer"
    email: "john@onebank.com"
  onCallSupport:
    - (111) 444-1234
    - (111) 444-1345

