build:
  version: "2.0"



loans:
  message: "Welcome to OneBank loans related QA APIs "
  contactDetails:
    name: "David Salt - QA Lead"
    email: "david@onebank.com"
  onCallSupport:
    - (333) 555-0202
    - (333) 666-0303